# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_auto_20171109_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='trains_Labeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
