# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_auto_20171115_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='label',
            name='presence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Presence'),
        ),
    ]
