# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0011_auto_20171115_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istcvcs_frame',
            name='bounding_boxes',
        ),
        migrations.RemoveField(
            model_name='istcvcs_frame',
            name='labels',
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='frame',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='query.istcvcs_Frame'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='frame',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='query.istcvcs_Frame'),
            preserve_default=False,
        ),
    ]
