# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0012_auto_20171118_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='query.LabelSource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='query.LabelSource'),
            preserve_default=False,
        ),
    ]
